package rc

// Generated by https://quicktype.io

type Info struct {
	Success bool      `json:"success"`
	Info    InfoClass `json:"info"`
}

type InfoClass struct {
	Version string `json:"version"`
	Build   Build  `json:"build"`
	Commit  Commit `json:"commit"`
}

type Build struct {
	NodeVersion string `json:"nodeVersion"`
	Arch        string `json:"arch"`
	Platform    string `json:"platform"`
	Cpus        int64  `json:"cpus"`
}

type Commit struct {
	Hash    string `json:"hash"`
	Date    string `json:"date"`
	Author  string `json:"author"`
	Subject string `json:"subject"`
	Tag     string `json:"tag"`
	Branch  string `json:"branch"`
}
