package rc

import "time"

// Generated by https://quicktype.io

type Rooms struct {
	Update  []Room `json:"update"`
	Remove  []Room `json:"remove"`
	Success bool   `json:"success"`
}

type Room struct {
	ID           string                 `json:"_id"`
	Name         string                 `json:"name,omitempty"`
	Type         string                 `json:"t"`
	UpdatedAt    time.Time              `json:"_updatedAt"`
	Default      *bool                  `json:"default,omitempty"`
	Fname        *string                `json:"fname,omitempty"`
	User         *RoomUser              `json:"u,omitempty"`
	CustomFields map[string]interface{} `json:"customFields,omitempty"`
	Ro           *bool                  `json:"ro,omitempty"`
}

type RoomUser struct {
	ID       string `json:"_id"`
	Username string `json:"username"`
}
